version: '3.9'
services:
  app:
    build: .
    container_name: take-the-long-way
    environment:
      - NODE_ENV=production
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./public/gpx:/app/public/gpx
      - ./public/kml:/app/public/kml
    restart: unless-stopped


